package syncer

import "gopkg.in/yaml.v3"

type SyncRun struct {
	// The root config file
	RootConfig *RootConfig
	// The subsection of the config file that is relevant to this run
	RunConfig RunConfig
	// The registries of this run
	Registry Registry
	// Where we want to copy destination files to
	DestinationWorkingDir string
}

func (r *RootConfig) AutogenMsg() string {
	// Separate the string so that it doesn't get picked up by the autogen script.
	return "THIS FILE IS AUTOGENERATED BY SYNCER " + " DO NOT EDIT"
}

type RunConfig struct {
	yaml.Node
}

func (r *RunConfig) Decode(v interface{}) error {
	return r.Node.Decode(v)
}
