# The version number for this config syntax.  syncer currently only supports version 1
version: 1
# General, shared config.  It is up to the logic to decide what to do with this
config:
  name: "syncer"
  primaryOwner: "infra-squad"
  linkerVarPath: ./internal/cli
  mainDir: ./cmd/syncer

children:
  - source: github.com/cresta/public-sync-modules/opensourcegocli
